@abstract
class_name SlashCurve
extends Object
## Abstract class for parameterized curves that are created from a SlashCurveData
## Meshes are generated by sampling points from this class


@abstract
func sample_point(t: float) -> SampleData

class SampleData:
	var tip_position: Vector3
	var hilt_position: Vector3
